#!/usr/bin/env bash
# Sync cross-repo ADR/decision pointers from the canonical orama-system docs/v2
# collection into a sibling repo's own ADR tree. Single source of truth, zero
# fragmentation (see docs/v2/27-git-governance-zero-fragmentation.md): the full
# decision lives ONCE in orama docs/v2/NN-*.md; downstream repos carry a generated
# pointer that links back and pins the canonical content hash.
#
# Usage:
#   sync-docs-v2-pointers.sh <target-repo>          # generate/update pointers
#   sync-docs-v2-pointers.sh --check <target-repo>  # verify in sync (CI/pre-commit); non-zero on drift
#
# The pointer is a deterministic function of the canonical doc + path mapping, so
# generation is idempotent (no timestamps embedded). --check regenerates in memory
# and diffs against the on-disk pointer: any drift (canonical edited, or pointer
# hand-edited) fails. This is the "ALWAYS SYNC in tandem" enforcement.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source_root="$(cd "$SCRIPT_DIR/../.." && pwd)"

CHECK=0
if [[ "${1:-}" == "--check" ]]; then
  CHECK=1
  shift
fi

target="${1:?target repo path required (e.g. ../../perplexity-api/Perpetua-Tools)}"
if [[ ! -d "$target/.git" ]]; then
  echo "skip: not a git repo: $target" >&2
  exit 0
fi
target="$(cd "$target" && pwd)"

ORAMA_GH="https://github.com/diazMelgarejo/orama-system/blob/main"

# canonical (orama, repo-relative) | pointer (target, repo-relative) | downstream ADR id
# Add a line per cross-repo pointer. Pipe-delimited.
MAPPINGS=(
  "docs/v2/30-multi-llm-router-caching-batching-decorator.md|docs/adr/ADR-002-multi-llm-router-caching-batching-decorator.md|ADR-002"
  "docs/v2/26-tdd-and-outsourced-review-doctrine.md|docs/adr/ADR-004-tdd-and-outsourced-review-doctrine.md|ADR-004"
)

sha256() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

# Emit the deterministic pointer body for one mapping to stdout.
render_pointer() {
  local canonical_rel="$1" adr_id="$2" canonical_abs="$3"
  local h title
  h="$(sha256 "$canonical_abs")"
  # H1 of the canonical doc, minus the leading "# NN — " numbering.
  title="$(grep -m1 '^# ' "$canonical_abs" | sed -E 's/^# [0-9]+ — //')"

  cat <<EOF
# ${adr_id} — ${title}  (POINTER)

> ⚠️ **GENERATED POINTER — DO NOT EDIT.**
> Canonical single source of truth: orama-system \`${canonical_rel}\`.
> GitHub: <${ORAMA_GH}/${canonical_rel}>
> Regenerated by orama-system \`scripts/git/sync-docs-v2-pointers.sh\`.
> Edit the canonical doc; never edit this pointer. Drift is caught by \`sync-docs-v2-pointers.sh --check\` (CI/pre-commit).
>
> \`canonical-sha256: ${h}\`

This decision's content lives **canonically** in the orama-system v2 spec
collection (\`docs/v2/\`) — the single ADR/decision home for the three-repo stack
(AlphaClaw → Perpetua-Tools → orama-system). \`MultiLLMRouter\` is *implemented* in
**this** repo (Perpetua-Tools, L2 runtime: \`orchestrator/supervisor.py\`), but the
*decision* is recorded once, in orama, per the zero-fragmentation doctrine
(orama \`docs/v2/27-git-governance-zero-fragmentation.md\`).

→ **Read the canonical decision:** <${ORAMA_GH}/${canonical_rel}>
EOF
}

rc=0
for m in "${MAPPINGS[@]}"; do
  IFS='|' read -r canonical_rel pointer_rel adr_id <<<"$m"
  canonical_abs="$source_root/$canonical_rel"
  pointer_abs="$target/$pointer_rel"

  if [[ ! -f "$canonical_abs" ]]; then
    echo "ERROR: canonical missing: $canonical_abs" >&2
    rc=1
    continue
  fi

  rendered="$(render_pointer "$canonical_rel" "$adr_id" "$canonical_abs")"

  if [[ "$CHECK" -eq 1 ]]; then
    if [[ ! -f "$pointer_abs" ]]; then
      echo "DRIFT: pointer missing: $pointer_abs (run without --check to generate)" >&2
      rc=1
    elif ! diff -q <(printf '%s\n' "$rendered") "$pointer_abs" >/dev/null 2>&1; then
      echo "DRIFT: $pointer_rel is out of sync with $canonical_rel" >&2
      diff <(printf '%s\n' "$rendered") "$pointer_abs" >&2 || true
      rc=1
    else
      echo "ok: $pointer_rel in sync with $canonical_rel"
    fi
  else
    mkdir -p "$(dirname "$pointer_abs")"
    printf '%s\n' "$rendered" >"$pointer_abs"
    echo "synced pointer → $pointer_abs  (← $canonical_rel)"
  fi
done

exit "$rc"
