#!/usr/bin/env bash
# install_coord_pulse.sh — install/uninstall 15-minute coord pulse (launchd)
# Usage:
#   ./scripts/install_coord_pulse.sh           # install (idempotent)
#   ./scripts/install_coord_pulse.sh --uninstall
#   ./scripts/install_coord_pulse.sh --status

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
# shellcheck source=../bin/orama-system/scripts/lib/openclaw-env.sh
source "$REPO_DIR/bin/orama-system/scripts/lib/openclaw-env.sh"
COORD_PULSE="$REPO_DIR/bin/orama-system/skills/hermes-harness/scripts/coord_pulse.sh"
LAUNCH_AGENTS="$HOME/Library/LaunchAgents"
PLIST_DEST="$LAUNCH_AGENTS/com.orama.coord-pulse.plist"
LABEL="com.orama.coord-pulse"
INTERVAL="${COORD_PULSE_INTERVAL_SEC:-900}"

PT_ROOT="${PERPETUA_TOOLS_ROOT:-${PERPETUATOOLSROOT:-}}"
if [ -z "$PT_ROOT" ]; then
    PT_ROOT="$(detect_perpetua_tools_root 2>/dev/null || true)"
fi

_status() {
    if launchctl list 2>/dev/null | grep -q "$LABEL"; then
        echo "OK $LABEL is loaded"
        launchctl list "$LABEL" 2>/dev/null | grep -E "PID|LastExitStatus" || true
    else
        echo "NOT LOADED $LABEL"
    fi
    if [ -f "$HOME/.openclaw/state/lan_peer/coord-pulse.log" ]; then
        echo "--- last 5 log lines ---"
        tail -5 "$HOME/.openclaw/state/lan_peer/coord-pulse.log"
    fi
}

_uninstall() {
    echo "Uninstalling $LABEL..."
    launchctl unload "$PLIST_DEST" 2>/dev/null || true
    rm -f "$PLIST_DEST"
    echo "Uninstalled."
}

_install() {
    echo "Installing coord pulse (interval=${INTERVAL}s)..."
    mkdir -p "$LAUNCH_AGENTS"
    mkdir -p "$HOME/.openclaw/state/lan_peer"

    WRAPPER="$HOME/.openclaw/state/lan_peer/coord-pulse-run.sh"
    cat > "$WRAPPER" << WRAPPER_EOF
#!/bin/bash
# Auto-generated by install_coord_pulse.sh
export ORAMA_SYSTEM_PATH="${REPO_DIR}"
export PERPETUA_TOOLS_PATH="${PT_ROOT}"
export OPENCLAW_DIR="${OPENCLAW_DIR:-$HOME/.openclaw}"
exec /bin/bash "${COORD_PULSE}"
WRAPPER_EOF
    chmod +x "$WRAPPER"
    chmod +x "$COORD_PULSE"

    cat > "$PLIST_DEST" << PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
    "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${WRAPPER}</string>
    </array>
    <key>StartInterval</key>
    <integer>${INTERVAL}</integer>
    <key>RunAtLoad</key>
    <false/>
    <key>StandardOutPath</key>
    <string>${HOME}/.openclaw/state/lan_peer/coord-pulse.log</string>
    <key>StandardErrorPath</key>
    <string>${HOME}/.openclaw/state/lan_peer/coord-pulse.log</string>
</dict>
</plist>
PLIST_EOF

    launchctl unload "$PLIST_DEST" 2>/dev/null || true
    launchctl load "$PLIST_DEST"

    echo "Installed: $LABEL"
    echo "  Wrapper: $WRAPPER"
    echo "  Log: $HOME/.openclaw/state/lan_peer/coord-pulse.log"
    echo "  Plan: bin/orama-system/skills/hermes-harness/references/coord-pulse-plan.md"
    _status
}

case "${1:-}" in
    --uninstall) _uninstall ;;
    --status)    _status ;;
    *)           _install ;;
esac
